[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://tubular-tapioca-d060e2.netlify.app"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_WEBPACK_USEPOLLING = "1"
  NEXT_EXPERIMENTAL_APP_DIR = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/@next/swc-*/**, !node_modules/next/dist/compiled/**, !node_modules/sharp/**"]

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 